# Generated by Django 5.2.14 on 2026-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
