# Generated by Django 5.2.14 on 2026-05-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
