# Generated by Django 5.2.14 on 2026-05-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addons',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
