# Generated by Django 5.2.14 on 2026-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='addons',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('classic', 'Классика'), ('slider', 'Слайдер'), ('seasonal', 'Сезонное')], default='classic', max_length=100),
        ),
    ]
