# Generated by Django 5.2.14 on 2026-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cartitem_addons_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('slider', 'Слайдер'), ('classic', 'Классика'), ('ice', 'Айс кофе'), ('matcha', 'Матча'), ('author', 'Авторские напитки'), ('food', 'Основное меню'), ('dessert', 'Десерты')], default='classic', max_length=100),
        ),
    ]
