# Generated by Django 5.2.14 on 2026-05-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('classic', 'Классика'), ('slider', 'Слайдер'), ('seasonal', 'Сезонное'), ('ice', 'Айс кофе'), ('matcha', 'Матча'), ('author', 'Авторские напитки'), ('food', 'Основное меню'), ('dessert', 'Десерты')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app.category'),
        ),
    ]
