# Generated by Django 5.2.14 on 2026-05-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
