# Generated by Django 5.2.14 on 2026-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_items_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.JSONField(default=list),
        ),
    ]
